workspace:
  path: src/

pipeline:
  run_kallisto:
    image: brettbj/continuous_analysis_base:latest
    commands:
      - ls /drone/src
      - mkdir -p drone
      - nose2 --plugin nose2.plugins.junitxml --junit-xml test
      - mv nose2-junit.xml drone/tests.xml
      - coverage run --branch test.py
      - coverage xml -o drone/coverage.xml test.py

      # run kallisto on a few simple tests
      - cd /kallisto/test
      - kallisto index -i transcripts.idx transcripts.fasta.gz
      - kallisto quant -i transcripts.idx -o output -b 100 reads_1.fastq.gz reads_2.fastq.gz
      - cp -R /kallisto/test/output /drone/src/output

      - jupyter nbconvert --to html --execute /drone/src/Drone_Plotting.ipynb

  push_to_github:
    image: brettbj/continuous_analysis_base:latest
    secrets: [ git_publish_key ]
    commands:
      # plot the results from a jupyter notebook
      - cd /drone/src

      # push the results back to github
      - git config user.email "brettbj@gmail.com"
      - git config user.name "Brett Beaulieu-Jones"
      - git config --global push.default simple
      - git remote set-url origin https://brettbj:$GIT_PUBLISH_KEY@github.com/greenelab/continuous_analysis.git

      - git add drone/*
      - git commit drone/* -m "Drone output [CI SKIP] [SKIP CI] ."

      - git fetch
      - git branch --set-upstream-to=origin/master master
      - git pull -s recursive -X ours
      - git push
      
branches: develop
